### PR TITLE
building and passing tests with GeoTools 22. (+1 squashed commit)

### PR DESCRIPTION
**Pull request by vickdw**
Squashed commits:
[a30164ac] GeoGig compiling with GeoTools 22-SNAPSHOT, still need to fix tests.

### CODE REVIEW

**Comment by groldan** [comment]
Hi @vickdw, looks like we're duplicating efforts, check out https://github.com/groldan/geogig/commits/2.0.x
Looks like that branch can be backported to 1.4.x up to e030499354b6c16bdbcf6118f0098c2297b7882c
Happy to set up a call to discuss if you're going to be working on geogig.

**Comment by vickdw** [comment]
Hi Gabe,

I'm the face of GeoGig here at Planet Federal now.  We still have clients
interested in implementing GeoGig and I've been trying to just keep GeoGig
updated as GeoTools and GeoServer move forward.  I just completed a PR for
the GeoServer plugin today.

Since you are heading towards a 2.0 release, should I wait for that, or
continue to work with 1.4?

David

**Comment by groldan** [comment]
Hi Dave, I'm afraid the changes in the 2.0 branch are going to be too disruptive for a while so I'd recommend you to stay on the stable one, but you can certainly cherry pick all those dependency upgrades. Also when doing a dependency upgrade it's better to make one commit per dep, that'll make it easier to track when it comes the time to go through Locationtech's QC process.

**Comment by groldan** [comment]
Hey @vickdw, closing this PR as outdated. Master moved to 2.0-SNAPSHOT already and branch 1.4.x does build with geotools 22-SNAPSHOT, so shouldn't be a problem.

**Pull request closed without merging**
